// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqFSLv-196A_ulNA5hYfRa8jiGkSGbTc',
    appId: '1:278618244409:web:19c69471168b03847314e8',
    messagingSenderId: '278618244409',
    projectId: 'sahajyo-syntax',
    authDomain: 'sahajyo-syntax.firebaseapp.com',
    storageBucket: 'sahajyo-syntax.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNiGvaEbY00GO9GW5zfe1DqxwqdSO_M6w',
    appId: '1:278618244409:android:7980667934c479c17314e8',
    messagingSenderId: '278618244409',
    projectId: 'sahajyo-syntax',
    storageBucket: 'sahajyo-syntax.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWZwuV4B0fjkGdGFjrCTh9EIUpiK7F1E',
    appId: '1:278618244409:ios:af7c417986cecd9c7314e8',
    messagingSenderId: '278618244409',
    projectId: 'sahajyo-syntax',
    storageBucket: 'sahajyo-syntax.appspot.com',
    iosBundleId: 'com.example.sahajyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWZwuV4B0fjkGdGFjrCTh9EIUpiK7F1E',
    appId: '1:278618244409:ios:af7c417986cecd9c7314e8',
    messagingSenderId: '278618244409',
    projectId: 'sahajyo-syntax',
    storageBucket: 'sahajyo-syntax.appspot.com',
    iosBundleId: 'com.example.sahajyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnqFSLv-196A_ulNA5hYfRa8jiGkSGbTc',
    appId: '1:278618244409:web:7fba9ceb86ab55557314e8',
    messagingSenderId: '278618244409',
    projectId: 'sahajyo-syntax',
    authDomain: 'sahajyo-syntax.firebaseapp.com',
    storageBucket: 'sahajyo-syntax.appspot.com',
  );
}
